-- ===================================================
-- Mantty Host - Schema de Base de Datos (Fase 3: Escalabilidad)
-- Rebranding: Unidad Habitacional (UH) Remanufactura
-- ===================================================

-- 1. Create Profiles Table (Extensions for Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  email TEXT,
  role TEXT DEFAULT 'residente' CHECK (role IN ('superadmin', 'admin_uh', 'residente', 'proveedor')),
  plan TEXT DEFAULT 'basic' CHECK (plan IN ('basic', 'plus', 'max')),
  property_id UUID, -- Link to UH
  extra_uh_capacity INTEGER DEFAULT 0, -- Support for hybrid plans
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Properties Table (Unidades Habitacionales)
CREATE TABLE IF NOT EXISTS public.properties (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  logo_url TEXT,
  admin_id UUID REFERENCES public.profiles(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Tickets/Reports Table
CREATE TABLE IF NOT EXISTS public.tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'pendiente' CHECK (status IN ('pendiente', 'en_progreso', 'completado', 'cancelado')),
  priority TEXT DEFAULT 'media' CHECK (priority IN ('baja', 'media', 'alta', 'critica')),
  created_by UUID REFERENCES public.profiles(id),
  property_id UUID REFERENCES public.properties(id),
  assigned_to UUID REFERENCES public.profiles(id), -- Provider or Admin
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;

-- 5. Performance Indexes (Escalabilidad)
CREATE INDEX IF NOT EXISTS idx_tickets_property_id ON public.tickets(property_id);
CREATE INDEX IF NOT EXISTS idx_tickets_created_by ON public.tickets(created_by);
CREATE INDEX IF NOT EXISTS idx_tickets_assigned_to ON public.tickets(assigned_to);
CREATE INDEX IF NOT EXISTS idx_tickets_status_priority ON public.tickets(status, priority);
CREATE INDEX IF NOT EXISTS idx_profiles_property_id ON public.profiles(property_id);
CREATE INDEX IF NOT EXISTS idx_properties_admin_id ON public.properties(admin_id);

-- 6. RLS Policies (Seguridad y Multi-tenancy)

-- PROFILES
DROP POLICY IF EXISTS "Users can view their own profile" ON public.profiles;
CREATE POLICY "Users can view their own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Admins can view members of their UH" ON public.profiles;
CREATE POLICY "Admins can view members of their UH" ON public.profiles
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.profiles p 
      WHERE p.id = auth.uid() AND p.role = 'admin_uh' AND p.property_id = public.profiles.property_id
    )
  );

-- PROPERTIES
DROP POLICY IF EXISTS "Admins can view their own UH" ON public.properties;
CREATE POLICY "Admins can view their own UH" ON public.properties
  FOR SELECT USING (admin_id = auth.uid());

DROP POLICY IF EXISTS "Members can view their UH details" ON public.properties;
CREATE POLICY "Members can view their UH details" ON public.properties
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE profiles.id = auth.uid() AND profiles.property_id = public.properties.id
    )
  );

-- TICKETS
DROP POLICY IF EXISTS "Residents can see their own tickets" ON public.tickets;
CREATE POLICY "Residents can see their own tickets" ON public.tickets
  FOR SELECT USING (auth.uid() = created_by);

DROP POLICY IF EXISTS "Admins can see their UH tickets" ON public.tickets;
CREATE POLICY "Admins can see their UH tickets" ON public.tickets
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE profiles.id = auth.uid() 
      AND profiles.role = 'admin_uh' 
      AND profiles.property_id = tickets.property_id
    )
  );

DROP POLICY IF EXISTS "Providers can see assigned tickets" ON public.tickets;
CREATE POLICY "Providers can see assigned tickets" ON public.tickets
  FOR SELECT USING (auth.uid() = assigned_to);

DROP POLICY IF EXISTS "Users can create tickets in their UH" ON public.tickets;
CREATE POLICY "Users can create tickets in their UH" ON public.tickets
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE profiles.id = auth.uid() AND profiles.property_id = tickets.property_id
    )
  );

DROP POLICY IF EXISTS "Admin and assigned can update tickets" ON public.tickets;
CREATE POLICY "Admin and assigned can update tickets" ON public.tickets
  FOR UPDATE USING (
    auth.uid() = assigned_to OR
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin_uh' AND profiles.property_id = tickets.property_id
    )
  );

-- 7. Trigger for New User Profile (Mantener)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, role)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    new.email,
    COALESCE(new.raw_user_meta_data->>'role', 'residente')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
